// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC82F5B5NUD9O39HSneehVfklE6ESVb6Lg',
    appId: '1:298895331243:web:3a1ee1e360d3c61fe9ccee',
    messagingSenderId: '298895331243',
    projectId: 'test-project-d1419',
    authDomain: 'test-project-d1419.firebaseapp.com',
    storageBucket: 'test-project-d1419.appspot.com',
    measurementId: 'G-ZLZ2NNZLXK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7htRl08aW7SQns5oTs-u94x2FGywlU5Y',
    appId: '1:298895331243:android:d0f7c43a83706d06e9ccee',
    messagingSenderId: '298895331243',
    projectId: 'test-project-d1419',
    storageBucket: 'test-project-d1419.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtVQikdF5hrUjgjDncm_M5A-e40FhHc_c',
    appId: '1:298895331243:ios:426f8299aedfe8abe9ccee',
    messagingSenderId: '298895331243',
    projectId: 'test-project-d1419',
    storageBucket: 'test-project-d1419.appspot.com',
    iosClientId: '298895331243-3pd7mtlefvf41tl7umre6s8ut9vl9454.apps.googleusercontent.com',
    iosBundleId: 'com.example.bus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtVQikdF5hrUjgjDncm_M5A-e40FhHc_c',
    appId: '1:298895331243:ios:426f8299aedfe8abe9ccee',
    messagingSenderId: '298895331243',
    projectId: 'test-project-d1419',
    storageBucket: 'test-project-d1419.appspot.com',
    iosClientId: '298895331243-3pd7mtlefvf41tl7umre6s8ut9vl9454.apps.googleusercontent.com',
    iosBundleId: 'com.example.bus',
  );
}
